[package]
name = "imgui-sys"
version = "0.0.22-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "Raw FFI bindings to dear imgui"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "external-ffi-bindings"]
build = "build.rs"

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["imm"] }

[build-dependencies]
cc = "1.0"
